name: simple-documents-stack
description: Plugin para configurar as documentacoes da sua stack.
types:
  - app
inputs:
  - label: Theme
    type: text
    default: "mkdocs"
    name: mkdocs_theme
    items:
      - "mkdocs"
      - "readthedocs"
hooks:
  - type: run
    trigger: after-render
    linux:
      - ./config.sh
    windows:
      - cmd /c ./config.sh
    mac:
      - sh ./config.sh